x-common-vars: &common-vars
  tty: true
  stdin_open: true
  ipc: host
  network_mode: host
  stop_grace_period: 1s
  environment:
    RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
    ROS_DOMAIN_ID: 40

services:
  thermal_uvc:
    image: scx/thermal_uvc:latest
    container_name: thermal_uvc
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER: infra
    << : *common-vars
    volumes:
      - /dev:/dev 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./packages:/home/infra/infra-ws/src:rw
    device_cgroup_rules:
      - "c 81:* rmw"
      - "c 189:* rmw"
    privileged: true
    command: bash

  gui:
    image: capstone:gui
    container_name: gui-capstone
    <<: *common-vars
    volumes:
        # X11 socket
        - /tmp/.X11-unix:/tmp/.X11-unix
        - $HOME/.Xauthority:/home/gui/.Xauthority
    command: ros2 launch foxglove_bridge foxglove_bridge_launch.xml address:=localhost port:=8740
    profiles: ['gui']