services:
  thermal_uvc:
    build:
      context: .
      dockerfile: Dockerfile
    image: scx/thermal_uvc:latest
    container_name: thermal_uvc
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY}:${XAUTHORITY}:ro
    network_mode: host
    privileged: true
    # restart: unless-stopped
